### ISSUE TITLE
Updating Aros

### ISSUE THREAD

**Issue by ngeorge1** [ivanamat/cakephp3-aclmanager#11]
There seems to be an issue with getting the parent id for the Aro in the new update. Worked good in the older version.

**Comment by ivanamat** [comment]
Hi @ngeorge1 

Can you tell me what you have in AclManager.aros?

In the previous version it was always generated with Groups, Roles and Users, all them requireds, now load the AROs that you specify in the variable AclManager.aros with a foreach, I will review this foreach, that is the one that generates the ARO.

**Comment by ngeorge1** [comment]
Hey,

This is what I have:
Configure::write('AclManager.aros', array('Groups', 'Roles', 'Users'));

**Comment by ivanamat** [comment]
I use the same configuration. Do you have many groups, roles and users?
I will create enough and try everything again.

**Comment by ngeorge1** [comment]
Yes I have many groups (5), roles(5) and users (10).

**Comment by ivanamat** [comment]
Hi, @ngeorge1 

Try latest version https://github.com/ivanamat/cakephp3-aclmanager/releases/tag/1.0.6

**Comment by ngeorge1** [comment]
Hey @ivanamat ,

Great, the latest update fixed the issue. Thanks

**Comment by ivanamat** [comment]
Hi @ngeorge1 

Thanks to you for report the error! ;)
