### ISSUE TITLE
unable to install with cakephp 3.4

### ISSUE THREAD

**Issue by dhananjayve** [ivanamat/cakephp3-aclmanager#13]
Hello
Please update this plugin for cakephp 3.4

**Comment by ivanamat** [comment]
Hi @dhananjayve, I'm using this plugin with CakePHP 3.4.7. Try updating everything with "composer update".

Regards!

**Comment by dhananjayve** [comment]
HI @ivanamat Please check this

PS D:\xampp\htdocs\cakelocal> composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - ivanamat/cakephp3-aclmanager 1.0.6 requires cakephp/plugin-installer ~0.0 -> satisfiable by cakephp/plugin-install
er[0.0.1, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9] but th
ese conflict with your requirements or minimum-stability.
    - ivanamat/cakephp3-aclmanager 1.0.5 requires cakephp/plugin-installer ~0.0 -> satisfiable by cakephp/plugin-install
er[0.0.1, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9] but th
ese conflict with your requirements or minimum-stability.
    - ivanamat/cakephp3-aclmanager 1.0.4 requires cakephp/plugin-installer ~0.0 -> satisfiable by cakephp/plugin-install
er[0.0.1, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9] but th
ese conflict with your requirements or minimum-stability.
    - ivanamat/cakephp3-aclmanager 1.0.3 requires cakephp/plugin-installer ~0.0 -> satisfiable by cakephp/plugin-install
er[0.0.1, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9] but th
ese conflict with your requirements or minimum-stability.
    - ivanamat/cakephp3-aclmanager 1.0.2 requires cakephp/plugin-installer ~0.0 -> satisfiable by cakephp/plugin-install
er[0.0.1, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9] but th
ese conflict with your requirements or minimum-stability.
    - ivanamat/cakephp3-aclmanager 1.0 requires cakephp/plugin-installer ~0.0 -> satisfiable by cakephp/plugin-installer
[0.0.1, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9] but thes
e conflict with your requirements or minimum-stability.
    - Installation request for ivanamat/cakephp3-aclmanager ~1.0 -> satisfiable by ivanamat/cakephp3-aclmanager[1.0, 1.0
.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6].

**Comment by ivanamat** [comment]
Hi @dhananjayve 

In my composer.json, in requirements I have the following, compare a see if it can serve you.

```
"require": {
        "php": ">=5.5.9",
        "cakephp/cakephp": "~3.2",
        "mobiledetect/mobiledetectlib": "2.*",
        "cakephp/migrations": "~1.0",
        "cakephp/plugin-installer": "~0.0",
        "cakephp/acl": "~0.2",
        "ivanamat/cakephp3-aclmanager": "~1.0",
        "ivanamat/cakephp3-bootstrap3": "dev-master",
        "ivanamat/cakephp3-markdown": "~1.0",
        "ivanamat/cakephp3-documents": "~1.0",
        "ivanamat/cakephp3-captcha": "dev-master"
    },
```
In the plugin the acl-manager de requirements are:

composer/installers": "*",

If you still have problems, can you copy paste your composer.json please?

Regards!

**Comment by diego182** [comment]
I guess the problem is that the plugin installer requires `"cakephp/plugin-installer": "~0.0",` while CakePHP require `"cakephp/plugin-installer": "~1.0"`

**Comment by pfuri** [comment]
@diego182 you are correct, CakePHP updated _cakephp/plugin-installer_ to 1.0 and that's why you are having issues.  I created a pull request to update the version about 2 weeks ago:  https://github.com/ivanamat/cakephp3-aclmanager/pull/16

Have you tried to install using _--ignore-platform-reqs_?

**Comment by ngrunfeld** [comment]
Same problem here, --ignore-platform-reqs doesnt fix it
