### ISSUE TITLE
Error: AclmanagerController could not be found.

### ISSUE THREAD

**Issue by domsen123** [ivanamat/cakephp3-aclmanager#19]
Hi,

if I follow you guide and want to open `http://localhost:8765/aclmanager` (admin is set to false) I get the error:

Error: AclmanagerController could not be found.

Plugin was installed by composer

What I'm doing wrong? :(

**Comment by ivanamat** [comment]
Hi @domsen123 

The AclmanagerController controller does not exist, it is AclManagerController, it changes the url by http://localhost:8765/AclManager or http://localhost:8765/aclManager, the route is case sensitive.

Try to change it and tell me if it works please.

Regards!
