### ISSUE TITLE
Missing Route, help :)

### ISSUE THREAD

**Issue by traeH-Heart** [ivanamat/cakephp3-aclmanager#22]
Missing Route  accessing http://myUrl.com/AclManager

Bootstrap
Configure::write('AclManager.aros', array( 'Roles', 'Users'));
Configure::write('AclManager.admin', false);

Plugin::load('Acl', ['bootstrap' => true]);
Plugin::load('AclManager', ['bootstrap' => true, 'routes' => true]);

> None of the currently connected routes match the provided parameters. Add a matching route to config/routes.php

**Comment by ivanamat** [comment]
Hi @iamdavidheartmercado 

It seems to be all right
* Is it a clean installation?
* Wich CakePHP version have you installed? 
* Have you write some route? 
* Is your url really camelcase? ( AclManager )

**Comment by traeH-Heart** [comment]
Is it a clean installation - Yes, I just install composer require ivanamat/cakephp3-aclmanager smoothly.

Wich CakePHP version have you installed -  "cakephp/cakephp": "3.4.*"

Have you write some route - Nope i set AclManager routes to TRUE

Is your url really camelcase? ( AclManager ) - I try used to used (AclManager, acl-manager) I'm using DashedRoute

**Comment by traeH-Heart** [comment]
Ops!  @ivanamat  

I tried to install your cakephp3-app. it works perfectly, may I have some wrong configuration on tables, I only used two tables (Roles , Users).

**Comment by traeH-Heart** [comment]
@ivanamat 

This is my current error 

> Error: A route matching "array ( 'controller' => 'settings', 'action' => 'edit', 'plugin' => 'AclManager', '_ext' => NULL, )" could not be found.

**Comment by traeH-Heart** [comment]
![image](https://user-images.githubusercontent.com/10648846/33832918-b1f48020-de32-11e7-807e-fc3d3f61ecef.png)

**Comment by ivanamat** [comment]
Hi @iamdavidheartmercado 

Please copy and paste your full route file to see if there is any route that is not well defined.

I have projects with personalized routes and I do not have any problems. I hope you copy and paste the file of routes to be able to know more.

I will not be able to check it until I get home.

Regards!

**Comment by traeH-Heart** [comment]
@ivanamat  

:) the issue is on my custom routes, It's working no, I set up my routes like this.. 
thanks

![image](https://user-images.githubusercontent.com/10648846/33833268-fb57215e-de33-11e7-9491-e771934f56e2.png)

**Comment by ivanamat** [comment]
Hi @iamdavidheartmercado 

The routes you have specified are already defined in plugin routes! You don't need to define them again.

If you need more help, do not hesitate, contact me. ;)

Regards!!

**Comment by traeH-Heart** [comment]
I got it. Thanks.

**Comment by davidspeijer** [comment]
I have the same issue, and I have no clue on how to fix it.

my routes.php file:
```
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

/**
 * Load all plugin routes. See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();
```


![acl](https://user-images.githubusercontent.com/20836703/37674387-161c5530-2c73-11e8-8f31-97476f0c7a6d.png)
