### ISSUE TITLE
Unable to update permissions ( Allow, Deny ) on some controllers .

### ISSUE THREAD

**Issue by traeH-Heart** [ivanamat/cakephp3-aclmanager#23]
Hello @Iván merry Xmas,

I have some issues on updating my permissions, some of my controllers unable to update permissions. 
when I change controller  BLOGS to deny it's perfectly working, but when I try to change the other controller ARTICLES nothing happens.

**Comment by traeH-Heart** [comment]
![image](https://user-images.githubusercontent.com/10648846/34319042-5b139306-e78b-11e7-8708-65953f8d2a56.png)

See this example the first controller I tried to deny it's working but the next Controller I try to change to Allow or Deny nothing happens.

Your ACL Manager is big help. Appreciated your worked

Thanks.

**Comment by ivanamat** [comment]
Hello @iamdavidheartmercado  I wish you a Merry Christmas for you, too. ;)

* How many controllers have you got?
* When you save changes, its to slow? (more than 30 seconds)

Thanks for appreciating the work done for CakePHP 3.x!

**Comment by ivanamat** [comment]
@iamdavidheartmercado 

I can see an index on the image you post, I suppose you have modified some part of the code. Have you made sure to close each part of the code correctly?

Can you check the configuration of your php and tell me what value max_input_vars has? It is also possible that this value is limited.

**Comment by ivanamat** [comment]
@iamdavidheartmercado 

I'm going to reinstall Kubuntu on my machine and it may take a while to answer again. When it's reinstalled, I'll respond right away.

Regards

**Comment by traeH-Heart** [comment]
Hello @ivanamat 

Sorry for delayed reply.


How many controllers have you got?
> My total acos 575

When you save changes, its to slow? (more than 30 seconds)
> not more than 30s.  when I save changes 20s to 25s

I can see an index on the image you post, I suppose you have modified some part of the code. Have you made sure to close each part of the code correctly?

> Nope. no modifications on actions, just controllers only.


my php.ini max_input_vars 
![image](https://user-images.githubusercontent.com/10648846/34351223-277342ca-e9d0-11e7-8a2b-06bfdb2e02e7.png)

**Comment by traeH-Heart** [comment]
Hi @ivanamat  

I found the problem on my ACL I have 575 Acos and I have  4 roles
when i try to save changes beyond 1000 max_input_vars nothing happens.

Acos 575  * 4 roles  = 2300 post params.

**Comment by joakim-emagine** [comment]
@traeH-divaD We ended having to resort to pagination, to get around this. It probably saves the first 1000 on the page and ignores the rest.

**Comment by ivanamat** [comment]
Hi @traeH-divaD and @joakim-emagine 

Sorry for having been slow to respond.

In the _php.ini_, update the **max_input_vars** config option, which is defaulted to a value of 1000.
