### ISSUE TITLE
"Call to a member function alias() on boolean" on method Paginate

### ISSUE THREAD

**Issue by byeloff** [ivanamat/cakephp3-aclmanager#24]
I have this problem:

Call a member function alias () on boolean

The error occurs on lines 90 and 149 of the AclController.php file

Could someone help me with this error?

Versions:
"cakephp/acl": "^0.2.6",
"cakephp/cakephp": "3.5.*",
"ivanamat/cakephp3-aclmanager": "^1.2",

Thank you very much

**Comment by ivanamat** [comment]
Hi @byeloff 

Have you configured AppController, bootstrap.php, created, groups, roles, users, logged in and executed "Update ACOs and AROs and set default values"?
