### ISSUE TITLE
Overwrite the view of the plugin

### ISSUE THREAD

**Issue by davidspeijer** [ivanamat/cakephp3-aclmanager#26]
I want to tweak the view a bit so it is using my style.

I created `/src/Template/Plugin/ivanamat/AclManager/Acl` and added copies of `index.ctp` & `permissions.ctp`. However they are not loaded (still using the regular template files in the vendor dir).

I used the info on
https://book.cakephp.org/3.0/en/plugins.html#overriding-plugin-templates-from-inside-your-application

I'm not using the admin prefix.

**Comment by ivanamat** [comment]
Hi! @davidspeijer 

It really does not work as described in the documentation. To overwrite the views you must overwrite the views without a vendor.

I have commented on the problem in the official CakePHP repository in a thread that is already open.

Read this: https://github.com/cakephp/docs/issues/5338#issuecomment-379062795

The overrided view example wthout vendor: http://test.ivanamat.es/timing/AclManager

Regards!

**Comment by ivanamat** [comment]
Hi @davidspeijer 

I created this issue https://github.com/cakephp/cakephp/issues/11910

As markstory comment in this [issue](https://github.com/cakephp/docs/issues/5338#issuecomment-379128080):
> The documentation should be how the code is working

Regards!
