### ISSUE TITLE
Deprecated warnings in CakePHP 3.6.4

### ISSUE THREAD

**Issue by davidspeijer** [ivanamat/cakephp3-aclmanager#28]
I'm receiving multiple deprecated warnings in CakePHP 3.6.4 using AclManager admin

Solved most of them myself by changing data() to getData() in the mentioned warnings.

I cannot figure out (quickly) on how to solve
Deprecated (16384): Setting data as a property will be removed in 4.0.0. Use withData() instead. - /home/public_html/vendor/ivanamat/cakephp3-aclmanager/src/Controller/AclController.php, line: 182

**Comment by ivanamat** [comment]
Hi @davidspeijer 

I will update this plugin soon, I will consider and review that. Thank you very much.

Best regards.
Iván Amat
