### ISSUE TITLE
Unable to use AclManager with another userModel

### ISSUE THREAD

**Issue by yarkm13** [ivanamat/cakephp3-aclmanager#29]
https://github.com/ivanamat/cakephp3-aclmanager/blob/bc6cfe9745ea5f7aae7da73a0cc6d976cbc57225/src/Template/Acl/permissions.ctp#L120

It's impossible to use AclManager if you have renamed user model because 'Users' is hardcoded into permissions check.

`Couldn't find Aros node identified by "Array ( [Aros0.model] => Users [Aros0.foreign_key] => 1 ) "`

Auth component configured as follows

    'authenticate' => [
        \Cake\Controller\Component\AuthComponent::ALL => ['userModel' => 'Members'],
    ],

and this setting can be accessed by

    $this->Auth->getConfig("authenticate");

**Comment by ivanamat** [comment]
Hi @yarkm13 

I will update this plugin soon, I will consider and review that. Thank you very much.

Best regards.
Iván Amat
