### ISSUE TITLE
Acl Already Loaded

### ISSUE THREAD

**Issue by stagistabm** [ivanamat/cakephp3-aclmanager#3]
The "Acl" alias has already been loaded with the following config: array ( ) which differs from array ( 'className' => 'Acl.Acl', )
RuntimeException

**Comment by ivanamat** [comment]
Hi @stagistabm  I'think it is solveved but not commit. I will review all the issues you mention me and push shortly. Thank you very much.

**Comment by stagistabm** [comment]
thanks!

**Comment by ivanamat** [comment]
Which release are you implement?

I think that was resolved in 1.0.4, or at least I thought I had solved the problem.
https://github.com/ivanamat/cakephp3-aclmanager/releases/tag/1.0.4

In a clean installation works for me. I will review the document README.md if there is any error. I will do a new installation by following steps README.md file.

**Comment by stagistabm** [comment]
composer.json 
        "ivanamat/cakephp3-aclmanager": "^1.0"

composer update doesn't find updates

i opened the bootstrap.php
and i find this:

Configure::write("AclManager.version", "1.0b");

i downloaded master and replaced files, nothing changes.

**Comment by ivanamat** [comment]
Ok, y wil do a clean installation following the README.md.

The Configure::write("AclManager.version", "1.0b");

**Comment by ivanamat** [comment]
@stagistabm Here a complete clean installation:

http://debug.ivanamat.es/

http://debug.ivanamat.es/users/login

User: demo
Password: demo

It's all new, the copy of CakePHP 3.2, models, controllers and database.

No Acl.Acl or image issues.

**Comment by stagistabm** [comment]
i resolved this issue, was a loadAll();

**Comment by ivanamat** [comment]
Great! I warn in the document README.md about this possibility. Thank you!
