### ISSUE TITLE
Failed ACO node lookup in permissions check.

### ISSUE THREAD

**Issue by yarkm13** [ivanamat/cakephp3-aclmanager#30]
Failed ACO node lookup in permissions check.

    Aco: controllers/AclManager/Acl/UpdateAcos [ROOT/vendor/cakephp/acl/src/Model/Table/PermissionsTable.php, line 92]

in the `acos` table all `AclManager` aliases is in lower case (`permissions`, `updateAcos`) 

To fix it i have change first letter to upper case (`Permissions`, `UpdateAcos`) in the DB

Or fix it in  the code and use correct action names

https://github.com/ivanamat/cakephp3-aclmanager/blob/bc6cfe9745ea5f7aae7da73a0cc6d976cbc57225/src/Template/Acl/index.ctp#L35
https://github.com/ivanamat/cakephp3-aclmanager/blob/bc6cfe9745ea5f7aae7da73a0cc6d976cbc57225/src/Template/Acl/index.ctp#L42
https://github.com/ivanamat/cakephp3-aclmanager/blob/bc6cfe9745ea5f7aae7da73a0cc6d976cbc57225/src/Template/Acl/index.ctp#L43
https://github.com/ivanamat/cakephp3-aclmanager/blob/bc6cfe9745ea5f7aae7da73a0cc6d976cbc57225/src/Template/Acl/index.ctp#L49
etc

**Comment by ivanamat** [comment]
Hi @yarkm13 

I will update this plugin soon, I will consider and review that. Thank you very much.

Best regards.
Iván Amat
