### ISSUE TITLE
Error: Cake\ORM\Entity::parentNode()

### ISSUE THREAD

**Issue by boyteenphonui** [ivanamat/cakephp3-aclmanager#31]
Error in: ROOT/vendor/ivanamat/cakephp3-aclmanager/src/Template/Acl/permissions.ctp, line 85

![screen shot 2018-08-21 at 6 56 28 pm](https://user-images.githubusercontent.com/11753393/44400064-0b596f00-a574-11e8-98da-d2773d87df96.png)

![screen shot 2018-08-21 at 7 06 23 pm](https://user-images.githubusercontent.com/11753393/44400435-54f68980-a575-11e8-9b67-548907cd4b6e.png)

![screen shot 2018-08-24 at 12 16 07 pm](https://user-images.githubusercontent.com/11753393/44567890-9b7afc80-a79e-11e8-8a08-3f9b651acfaa.png)

I have done all these steps
https://github.com/ivanamat/cakephp3-aclmanager#implement-parentnode-function-in-group-entity

Can't call $ parentNode = $ aro-> parentNode ();

**Comment by boyteenphonui** [comment]
It does not work with the plugin
![screen shot 2018-08-24 at 1 01 38 pm](https://user-images.githubusercontent.com/11753393/44567733-037d1300-a79e-11e8-9121-dca3718e8e76.png)
![screen shot 2018-08-24 at 1 02 59 pm](https://user-images.githubusercontent.com/11753393/44567742-0d067b00-a79e-11e8-821a-0fa84d75c9ad.png)

**Comment by ivanamat** [comment]
Hi @boyteenphonui 

It should be:
>Configure::write('AclManager.aros', array('Groups', 'Roles', 'Users'));

and not:
>Configure::write('AclManager.aros', array('Group.Groups', 'Role.Roles', 'User.Users'));

Best regards
Iván Amat

**Comment by MathRat** [comment]
Same problem here:

i added this in AclController.php

       $this->loadModel('Db.DbUsers');
        $this->loadModel('Db.Laender');
        debug($this->DbUsers);
        debug($this->Laender);
        $user = $this->DbUsers->get(1);
        debug($user->parentNode());

This is the result:

    object(Cake\ORM\Table) {

	'registryAlias' => 'DbUsers',
	'table' => 'db_users',
	'alias' => 'DbUsers',
	'entityClass' => 'Cake\ORM\Entity',
	'associations' => [],
	'behaviors' => [],
	'defaultConnection' => 'default',
	'connectionName' => 'default'

    }

    object(Db\Model\Table\LaenderTable) {

	'registryAlias' => 'Db.Laender',
	'table' => 'laender',
	'alias' => 'Laender',
	'entityClass' => 'Db\Model\Entity\Laender',
	'associations' => [
		(int) 0 => 'regionen'
	],
	'behaviors' => [],
	'defaultConnection' => 'default',
	'connectionName' => 'default'

    }

Both Models are defined in plugin "Db"

My config:

    Configure::write('AclManager.aros', array('DbGroups', 'DbRoles', 'DbUsers'));

You see a difference in entityClass. My users table seems not to get used. that's the reason the function parentNode() is not found. Debugging same code in i.e. Db/BenutzerController.php shows both entitiyClass Db\Model\Entity\ ...

**Comment by ivanamat** [comment]
Hi, @MathRat 

Have you tried this?
```
Configure::write('AclManager.aros', array('dbGroups', 'dbRoles', 'dbUsers'));
```

Do you have the parentNode() function implemented in your entities? It should be implemented.
https://github.com/ivanamat/cakephp3-aclmanager#implement-parentnode-function-in-group-entity

**Comment by MathRat** [comment]
Hi @ivanamat,

i tried it, same issue. Objecttype is still Cake\ORM\Entity, not Db\...

the parentNode() is implemented. In debug code above, it returns group_id. I'm sure, i configured erverything. Is it possible, that your plugin is not working with plugin models?

![image](https://user-images.githubusercontent.com/3359532/81957152-7ed6c600-960c-11ea-8ad3-1a6e638bf01d.png)

![image](https://user-images.githubusercontent.com/3359532/81957229-9746e080-960c-11ea-8539-216cd69ab7c6.png)

**Comment by ivanamat** [comment]
How are you loading db plugin? PSR-4, in the bootstap.php, extending ApplicationBase?

**Comment by MathRat** [comment]
Hi,

because of your question i tried multiple combinations. Autoloaded PSR-4, loaded by bootstrap.php or Application.php Because of i don't need auth in application, i implemented auth in Db and extends  Db\AppController in AclManager AppController. i tried to implement auth in application and extend ApplicationBase. All of this did not helped. Entity is still missing parentNode() because it's Cake\ORM\Entity not Db\Model\Entity\DbUsers

**Comment by ivanamat** [comment]
Can you provide me the URL of the Db plugin please?
Do you load the AclManager or Db plugin first?
