### ISSUE TITLE
Error: AclManagerController could not be found.

### ISSUE THREAD

**Issue by gurpreetkaur87** [ivanamat/cakephp3-aclmanager#32]
To Access the plugin I am navigating to http://www.domain.com/AclManager, But I am facing the error that AclManagerController could not be found. So please help me out.

**Comment by royalfoxie** [comment]
Try clear cache. It's work for me.

**Comment by ivanamat** [comment]
Hi @gurpreetkaur87 

Sorry I didn't answer any sooner, I've left several things a little unattended and among them, this plugin.

I suppose that after more than a year, by now you should have it fixed, if not, please, reopen this issue when you need it.

Best regards
Iván Amat

**Comment by ivanamat** [comment]
Hi @gurpreetkaur87

Sorry I didn't answer any sooner, I've left several things a little unattended and among them, this plugin.

I suppose that after more than a year, by now you should have it fixed, if not, please, reopen this issue when you need it.
