### ISSUE TITLE
AROs not updating automatically

### ISSUE THREAD

**Issue by Nucleuz** [ivanamat/cakephp3-aclmanager#34]
Hi,
Should it be necessary to access the AclManager and click Update AROs every time I e.g. create a User? In the aros table, the alias get populated with the user's username. However, it only gets updated after I access the AclManager and click Update AROs. It is just NULL right after I create the user. Isn't it supposed to get updated right away?

I've just created at new project from scratch (with CakePHP 3.4, cakephp3-aclmanager 1.3, cakephp/acl 0.2), and it is the same problem.

I hope you can help. Thanks in advance.

**Comment by ivanamat** [comment]
Hi @Nucleuz 

Sorry I didn't answer any sooner, I've left several things a little unattended and among them, this plugin.

I suppose that after much time, by now you should have it fixed, if not, please, reopen this issue when you need it.

Best regards
Iván Amat
