### ISSUE TITLE
Undefined property: AclController::$lookup

### ISSUE THREAD

**Issue by zahari4i** [ivanamat/cakephp3-aclmanager#36]
Hi. I started getting some errors while managing the permission for groups, roles, users. The error is:
Undefined property: AclController::$lookup in /vendor/ivanamat/cakephp3-aclmanager/src/Controller/AclController.php on line 409.
Tried with CakePHP version 3.6 and 3.8.
This property doesn't seem to be defined in the class or in any other extended class and it's not used anywhere in the controller.
Is this property really needed?

Removing it doesn't seem to affect any functionality.

Thank you

**Comment by ivanamat** [comment]
Hi @zahari4i 

I will update this plugin soon, I will consider and review that. Thank you very much.

Best regards.
Iván Amat

**Comment by zahari4i** [comment]
Hi Ivan, thanks a lot for getting back. Do you plan in adding support for the 4th version?

Regards

Sergiu
