### ISSUE TITLE
using acl manager in plugin only

### ISSUE THREAD

**Issue by MathRat** [ivanamat/cakephp3-aclmanager#37]
Hi,

i'm trying to use aclmanager for manage acl for a plugin, not for whole application. is it possible to load aclmanager only when in "parent" plugin and to use parental auth methods?

sry my bad english :)

**Comment by ivanamat** [comment]
Hi @MathRat 

You can use **AclManager.ignoreActions** this was made for that purpose

> AclManager.ignoreActions Ignore all plugins, controllers and actions you don't want to add to your ACLs.

Best regards
Iván Amat
