### ISSUE TITLE
Error: AclManager.AclController could not be found.

### ISSUE THREAD

**Issue by aloisejulian** [ivanamat/cakephp3-aclmanager#5]
Tengo el siguiente Issue cuando entro a dominio.com/AclManager/Acl me arroja el siguiente error:

Error: AclManager.AclController could not be found.

Error: Create the class AclController below in file: /var/www/dominio.com/plugins/AclManager/src/Controller/AclController.php

Pero el archivo existe... Cual es el motivo?

**Comment by ivanamat** [comment]
Hola @aloisejulian 

¿Has revisado y cargado en tu archivo bootstrap.php el plugin de Acl y AclManager como se indica?

```
Plugin::load('Acl', ['bootstrap' => true]);
Plugin::load('AclManager', ['bootstrap' => true, 'routes' => true]);
```

¿Has probado simplemente http://dominio.com/AclManager  o http://dominio.com/AclManager/permisssions ? Es posible que alguna ruta se me haya escapado o haya hecho alguna modificación.

Saludos!

**Comment by aloisejulian** [comment]
hola @ivanamat 

Los plugin:load esta en el archivo: /var/www/proyecto/config/bootstrap.php
El AclManager esta en: /var/www/proyecto/plugins/AclManager/src/Controller/AclController.php

Cuando entro a http://dominio.com/AclManager me tira el error reportado mas arriba: Error: AclManager.AclController could not be found.

Si entro a http://dominio.com/AclManager/permisssions:
Error: AclManager.PermisssionsController could not be found.
Error: Create the class PermisssionsController below in file: /var/www/proyecto/plugins/AclManager/src/Controller/PermisssionsController.php

Si entro a http://dominio.com/AclManager/acl/permisssions: Error: AclManager.AclController could not be found.

Yo segui todos los pasos de tu guia, y esto lo estoy probando en u ncake desde 0. Ya que pense que era un problema de mi proyecto, por eso inicie uno nuevo para probar exclusivamente esto. 

Gracias! Saludos!

**Comment by ivanamat** [comment]
Hola @aloisejulian 
¿Has syncronizado los ACOS y los AROS por consola?

**Comment by aloisejulian** [comment]
@ivanamat 
Lo he intentado con el siguiente comando: bin/cake acl_extras aco_sync

pero me tira  error:
Exception: Class AclManager\Controller\AclController does not exist in [/home/aloisejulian/workspace/aclCake/vendor/cakephp/acl/src/AclExtras.php, line 389]
2016-11-16 17:04:17 Error: [ReflectionException] Class AclManager\Controller\AclController does not exist

**Comment by ivanamat** [comment]
@aloisejulian ¿Lo hass instalado manualmente descargando y moviendo al directorio, mediante gitsubmodule o mediante composer?

**Comment by aloisejulian** [comment]
@ivanamat  Tu plugin lo isntale manualmente. El acl de cake(https://github.com/cakephp/acl) lo instale mediante composer

**Comment by ivanamat** [comment]
@aloisejulian ¿Puedes intentar instalarlo mediante composer porfavor? y me dices si te sucede lo mismo.

**Comment by aloisejulian** [comment]
@ivanamat Dale, instalo mediante composer y te aviso... Gracias desde ya!

**Comment by ivanamat** [comment]
;) A ti!

**Comment by aloisejulian** [comment]
Ivan, perdon por la tardanza, recien ahora pude probarlo. Lo instale por composer y anduvo... Ahora cuando entro a /AclManager

AclNode::node() - Couldn't find Aros node identified by "Array ( [Aros0.model] => Users [Aros0.foreign_key] => ) "
Gracias

**Comment by ivanamat** [comment]
Buenas @aloisejulian 

Perdona esta vez tu, no he podido conectarme hasta hoy. Lo que comentas ya es tema de que no están los aros o acos creados aún o como se debe.

Por un lado, en el AppController o en Users, Roles y Groups deberás agregar:

    $this->Aunth->allow('*')

Lo que permitirá que naveges por toda la web sin restricciones. Vas Grupos, creas un grupo, luego lo mismo con Roles y por últmo con Usuario. Tras haber hecho esto, ejecutas el comando por consola que comento para actualizar los Acos y los Aros:

    bin/cake acl_extras aco_sync

Hecho esto, si no me equivoco, lo único que te queda es quitar el $this->Aunth->allow() allá donde lo hayas puesto e iniciar sesión con el usuario que acabas de crear.

Con esto debería funcionar. Cualquier otro error comenta y lo revisamos.

Saludos!

**Comment by aloisejulian** [comment]
@ivanamat,
Ahi pude hacerlo funcionar!  
Ademas de ejecutar este comando:

`bin/cake acl_extras aco_sync`

tuve que ejecutar este tambien:

`bin/cake acl grant Groups.1 controllers`

Muchisimas gracias por la ayuda! 
Un saludo!

**Comment by inimist** [comment]
This is so important thread and I had to translate page using Google Translator to make it useful for myself. I still am having the same issue, of 
Error: AclManager.AclController could not be found.

Error: Create the class AclController below in file: C:\wamp\www\d3\plugins\AclManager\src\Controller\AclController.php

I am going to install it using composer and will come back to thread to post the result.

**Comment by ivanamat** [comment]
Hi @inimist 

Try new release!
