### ISSUE TITLE
Roles AND groups table?

### ISSUE THREAD

**Issue by LDSign** [ivanamat/cakephp3-aclmanager#6]
Hi

Could you explain in some short words why there is a roles AND a groups table for setting up your plugin? The default configuration of acl only requires a role table...

I am confused... :)

Thanks,
Frank

**Comment by ivanamat** [comment]
Hi @LDSign,

Sorry for taking so long to answer, I've been a busy few days and I could not connect to answer you.

On line 95 of the AclManagerComponent.php file the "arosBuilder()" function should read the hoops to be used from "Configure :: read ( 'AclManager.aros');", considering the order. The function made it static, "temporarily", to be able to verify that it worked.

See: https://github.com/ivanamat/cakephp3-aclmanager/blob/master/src/Controller/Component/AclManagerComponent.php#L95

I hope to be able to update the function soon.

Regards, Iván.

**Comment by ivanamat** [comment]
This issue is solved in latest stable version.

CakePHP 3.x - AclManager v1.0.5
https://github.com/ivanamat/cakephp3-aclmanager/releases/tag/1.0.5
