### ISSUE TITLE
cities is not added on ACOs

### ISSUE THREAD

**Issue by ramsesrom** [ivanamat/cakephp3-aclmanager#7]
I have bake cities on my project but when I update the ACOs nothing is added. But when I change the name of the  table to citys from cities it was added correctly.
![citys](https://cloud.githubusercontent.com/assets/7602450/21918862/9c44a216-d990-11e6-8b32-4b4b3b936e1d.png)

**Comment by ivanamat** [comment]
Hi! Try update acos and aros throught cake command:
```
bin/cake acl_extras aco_sync
```
Tell me if that solved your problem and I'll keep that in mind when I resolve Issue #4 ;) Thanx!

**Comment by ramsesrom** [comment]
yup i also did that several times

**Comment by ivanamat** [comment]
Looks like something from the conventions, I've been looking for information on this topic and there are more people that happens to it with the same table name.

**Comment by aio-software** [comment]
Yes, that works. But I'd like to use the buttons that are provided.

**Comment by ivanamat** [comment]
Hi @lucky1968 I will try to solve the problem as soon as possible so that it works correctly.

Thanks and regards!
