### ISSUE TITLE
Admin routing

### ISSUE THREAD

**Issue by aio-software** [ivanamat/cakephp3-aclmanager#8]
In aclmanager/config/bootstrap.php I have set `Configure::write('AclManager.prefix', 'admin');` but when visiting _AclManager/admin/Acl/_ I get an **Error: AclManager.AdminController could not be found.**
I also Duplicated all controllers and Templates into their respective 'Admin'-namespace without any result. Maybe this is not even necessary?
Do I need to do some more stuff to make it work in with the 'admin'-prefix? Like adding some additional prefix-routing in aclmanager/config/routes.php?

**Comment by ivanamat** [comment]
I think you should modify many things, possibly more feasible add a rewrite rule in the .htaccess. Something like this:

------------ .htaccess ------------
RewriteEngine on
RewriteRule ^admin/Acl/?$ Acl
RewriteRule ^admin/Acl/(.*) Acl/$1
------------ end .htaccess ------------

Maybe this way will be easier.

Greetings and thanks!

**Comment by aio-software** [comment]
So you don't actually use the `Configure::write('AclManager.prefix', 'admin');` setting in your code?

**Comment by aio-software** [comment]
I have copied the controllers and views into the respective Controller/Admin/ and Template/Admin/ folders but visiting localhost/admin/AclManager/Acl/ gives me an error:
Error: AclManagerController could not be found.
Can you tell me what to add to make this work in the admin area and so it identifies AclManager/ as the pluginname instead of the Controller?
I guess it should be done without rewriting .htaccess rules but I'm probably overlooking something?

**Comment by ivanamat** [comment]
This issue is solved in latest stable version.

CakePHP 3.x - AclManager v1.0.5
https://github.com/ivanamat/cakephp3-aclmanager/releases/tag/1.0.5
