### ISSUE TITLE
Couldn't find Aros node identified by

### ISSUE THREAD

**Issue by huesoamz** [ivanamat/cakephp3-aclmanager#9]
Hi, 

When I access to 
.../AclManager/acl/permissions/Roles or
.../AclManager/acl/permissions/Users

I got this message:

> AclNode::node() - Couldn't find Aros node identified by "Array ( [Aros0.model] => Users [Aros0.foreign_key] => )

![sin titulo](https://cloud.githubusercontent.com/assets/3308717/22293865/0665f4e8-e2f0-11e6-8346-08521d9c7093.png)
http://i.imgur.com/vixIm04.png

Could you please help me? or tellme if I doing some wrong?

Thanks in advance!

**Comment by huesoamz** [comment]
Fixed!, I created the users and gruops but I comment a part of the code on appController for create without a user login in, so I login IN as admin and works!

Thanks!

**Comment by ivanamat** [comment]
Hello, I'm sorry I was slow to respond, I've been pretty busy for a few days. 

I may have forgotten to explain something in the documentation. I have to review all documentation and take time to review the issues. Sorry for not helping you solve the problem.

Regards and thank you!
